#%RAML 0.8

title: Neutrino
version: 1.0.0
mediaType: application/json
protocols: [HTTP, HTTPS]
baseUri:
documentation:
  - title: Introduction
    content: |
      `Neutrino`

schemas:
  - RES_DomainException: !include schemas\response\error_400.json
  - RES_ValidationException: !include schemas\response\error_422.json
  - RES_ServerException: !include schemas\response\error_500.json

traits:
  - Filtereble: !include traits\filtarable.raml
  - Truncatable: !include traits\truncatable.raml
  - Paginatable: !include traits\paginatable.raml
  - Authenticatable: !include traits\authenticatable.raml

