headers:
  Authorization:
    displayName: Authentication Token

    description: |
      The authentication token returned by a successful login.
      Sent as a `Bearer` token.

      `Bearer <token>`

      A pair of tokens is used to maintain the consistancy of the token refreshing process.
      Authenticated routs will return the following header values when the authentication token nears expiry.

      `X-Token-Refresh` : `0` - When the route is authenticated using the `Old Token` of the pair
      `X-Token-Refresh` : `1` - When the route is authenticated using the `New Token` of the pair

    type: string
    required: true
