queryParameters:
  page:
    displayName: Paginate

    description: |
      Pagination details that contains
        - page (integer) requested page
        - perPage (integer) records per page

      `?paging={"page":1, "perPage":10}`

    type: string
    required: false
