queryParameters:
  fields:
    displayName: Return Fields

    description: |
      Fields to return in the response dataset. The fields to return are given as follows.

      `?fields=["field_1", "field_2", ...]`

    type: string
    required: false
